### ISSUE TITLE
Usage question in regard to the models,..

### ISSUE THREAD

**Issue by Selur** [Kiyamou/VapourSynth-RealSR-ncnn-Vulkan#3]
Got the models in RealSR\models\models-DF2K- and RealSR\models\models-DF2K_JPEG-foöders and rnsv.dll inside the RealSR-folder.
Does the filter automatically switch between the models or is there a way do select a model?

Cu Selur

**Comment by Kiyamou** [comment]
In fact, only model in `models-DF2K` is used now.

The model in `models-DF2K_JPEG` may be more suitable for single pictures.
Maybe I will add an option for selecting models in the future.

**Comment by Selur** [comment]
Yes, that would be nice. :)

**Comment by Kiyamou** [comment]
I add a parameter `model` to select models.

It is interesting that the model `models-DF2K_JPEG` has a better result in my test (I test a 720p video with noise). Thank you for your suggestion. I almost ignored this model.

**Comment by Selur** [comment]
Nice. I like it thanks!
