### ISSUE TITLE
大佬是否对Realcugan感兴趣呢

### ISSUE THREAD

**Issue by Chikage0o0** [Kiyamou/VapourSynth-RealSR-ncnn-Vulkan#6]
目前realcugan的ncnn的实现已经差不多稳定，大佬有否考虑移植为VS的插件
目前其模型在实际使用中效果不错，大部分情况优于realsr
https://github.com/nihui/realcugan-ncnn-vulkan

**Comment by Kiyamou** [comment]
一直没来得及看，我以为已经有人移植了Orz...

要是没有人做的话，我找时间看一看啊

**Comment by Chikage0o0** [comment]
> 一直没来得及看，我以为已经有人移植了Orz...
> 
> 要是没有人做的话，我找时间看一看啊

谢谢啊

**Comment by Kiyamou** [comment]
https://github.com/Kiyamou/VapourSynth-RealCUGAN-ncnn-Vulkan

基本上移植完成了

目前已知的问题是在放大倍数较高（3x 和 4x）且开启 TTA 时，tilesize 需要设置成较小的值，不然会直接崩溃...
（这个问题其实在 RealSR 中也有，而且 RealSR 似乎无论开不开 TTA 都需要较小的 tilesize）
这个问题我得研究研究 Orz... 不过目前是能用哒~

**Comment by Chikage0o0** [comment]
> https://github.com/Kiyamou/VapourSynth-RealCUGAN-ncnn-Vulkan
> 
> 基本上移植完成了
> 
> 目前已知的问题是在放大倍数较高（3x 和 4x）且开启 TTA 时，tilesize 需要设置成较小的值，不然会直接崩溃... （这个问题其实在 RealSR 中也有，而且 RealSR 似乎无论开不开 TTA 都需要较小的 tilesize） 这个问题我得研究研究 Orz... 不过目前是能用哒~

应该是爆显存大概

**Comment by Kiyamou** [comment]
> 应该是爆显存大概

应该是这个原因
